import esbuild from 'esbuild';
import { appendFileSync, readFileSync } from 'node:fs';
import { builtinModules } from 'node:module';
import path from 'node:path';
import process from 'process';

// Shared with release-check.mjs, which re-checks the same threshold against an
// already-built main.js — both read this key so the two checks can't drift apart.
// Obsidian loads every enabled plugin's `main.js` at vault startup — a size
// regression is a user-facing cost, not just a build metric. Bump this in
// package.json if the plugin legitimately grows, but bump it deliberately.
// Analysis native scroll restoration and accessible row targets received a measured
// 1 KiB increase per artifact (1841 KiB main / 181 KiB CSS); dependency scope is unchanged.
const { mainJsBudgetBytes: MAIN_JS_BUDGET_BYTES } = JSON.parse(
  readFileSync('package.json', 'utf8'),
).release;
const thirdPartyNotices = readFileSync('THIRD_PARTY_NOTICES.txt', 'utf8').trim();
if (thirdPartyNotices.length === 0 || thirdPartyNotices.includes('*/')) {
  throw new Error('Third-party notices must be nonempty and safe to embed in a JavaScript comment');
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
/*
${thirdPartyNotices}
*/
`;

const args = process.argv.slice(2);
const prod = args.includes('production');
const analyze = args.includes('analyze');

// Obsidian strips inline source maps from dev builds unless main.js ends with
// this exact marker comment: https://forum.obsidian.md/t/source-map-trimming-in-dev-builds/87612
const nosourcemapPlugin = {
  name: 'nosourcemap-marker',
  setup(build) {
    build.onEnd(() => {
      if (!prod) {
        appendFileSync('main.js', '\n/* nosourcemap */');
      }
    });
  },
};

/** @type {import('esbuild').Plugin} */
const taskSearchWorkerPlugin = {
  name: 'task-search-worker',
  setup(build) {
    build.onResolve({ filter: /^abyss-task-search-worker$/ }, () => ({
      path: 'abyss-task-search-worker',
      namespace: 'task-search-worker',
    }));
    build.onLoad({ filter: /.*/, namespace: 'task-search-worker' }, async () => {
      const worker = await esbuild.build({
        entryPoints: ['src/tasks/infrastructure/search/taskSearch.worker.ts'],
        bundle: true,
        platform: 'browser',
        format: 'iife',
        target: 'es2021',
        write: false,
        metafile: true,
        minify: prod,
        mangleProps: prod ? /_abyssPrivate$/ : undefined,
      });
      const source = '/* abyss-task-search-worker */' + worker.outputFiles[0].text;
      return {
        contents: 'export default ' + JSON.stringify(source),
        loader: 'js',
        watchFiles: Object.keys(worker.metafile.inputs).map((file) => path.resolve(file)),
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: analyze ? 'silent' : 'info',
  sourcemap: prod ? false : 'inline',
  drop: ['debugger'],
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  // Opt in only audited TypeScript private members; public, Obsidian and persisted keys
  // never carry this suffix. Quoted/indirect property names must remain unmangled.
  mangleProps: prod ? /_abyssPrivate$/ : undefined,
  mangleQuoted: false,
  metafile: prod || analyze,
  plugins: [taskSearchWorkerPlugin, nosourcemapPlugin],
});

if (prod) {
  const result = await context.rebuild();
  if (analyze) {
    console.info(await esbuild.analyzeMetafile(result.metafile, { verbose: false }));
  }
  checkSizeBudget(result.metafile);
  process.exit(0);
} else {
  await context.watch();
}

function checkSizeBudget(metafile) {
  const bytes = Object.values(metafile.outputs).reduce((total, output) => total + output.bytes, 0);

  if (bytes > MAIN_JS_BUDGET_BYTES) {
    console.error(
      `main.js is ${(bytes / 1024).toFixed(1)} KB, over the ${(MAIN_JS_BUDGET_BYTES / 1024).toFixed(0)} KB budget in esbuild.config.mjs. ` +
        'Check for an accidentally-bundled dependency, or raise the budget deliberately.',
    );
    process.exit(1);
  }
}
